name: notify_releases
description: A simple console application.
version: 0.0.1
#homepage: https://www.example.com
#author: Antonin <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "0.11.3+9"
  mailer: "1.1.4"

#dev_dependencies:
#  test: ^0.12.0
