name: notify_releases
description: bla
version: 0.0.1
#homepage: https://www.example.com
#author: Antonin <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'
#  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "0.12.0"
  mailer: "2.0.2"

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.0
